name : workflow commands
on: [push]

jobs:
  testing-wf-commands : 
    runs-on : ubuntu-latest
    steps :
      - name : "Display error msg"
        run : echo "::error::Missing something"
